export const db = {
  produtos: [
    {
      id: "0",
      title: "Suporte p/ Headset Ozone Portal RGB Hub",
      categorias: {
        categoria: "Periféricos",
        subCategoria: "Audio",
        subCategoria2: null,
      },
      specs: [
        { title: "Marca", content: ["Ozone"] },
        { title: "Canais", content: ["7.1"] },
        { title: "Tipo", content: ["Suporte"] },
        { title: "Tipo", content: ["Placa de som"] },
        { title: "Sem fios", content: ["Não"] },
        { title: "Portas I/O", content: ["USB 3.0 (x3)"] },
      ],
      img: [
        {
          original: "assets/img/produtos/1_332_17.jpg",
          thumbnail: "assets/img/produtos/1_332_17.jpg",
        },
      ],
      precos: { normal: "39.90", desconto: "27.90" },
      ribbons: { novo: true, saldos: true },
      vendas: 0,
    },

    {
      id: "1",
      title: "Subwoofer Edifier T5 70W Preto",
      categorias: {
        categoria: "Periféricos",
        subCategoria: "Audio",
        subCategoria2: "Colunas",
      },
      specs: [
        { title: "Marca", content: ["Edifier"] },
        { title: "Canais", content: ["0.1"] },
        { title: "Tipo", content: ["Subwoofer"] },
        { title: "Sem fios", content: ["Não"] },
        { title: "Portas I/O", content: ["RCA"] },
      ],
      img: "1_335_2.jpg",
      precos: { normal: "129.90", desconto: null },
      ribbons: { novo: true, saldos: false },
      vendas: 1,
    },
    {
      id: "2",
      title: "Mini PC GMK NucBox",
      categorias: {
        categoria: "Computadores",
        subCategoria: "Desktops",
        subCategoria2: "Workstation",
      },
      specs: [
        { title: "Marca", content: ["GMK"] },
        { title: "Armazenamento", content: ["SSD 256GB"] },
        { title: "CPU", content: ["Intel Celeron J4125"] },
        { title: "RAM", content: ["8GB"] },
        { title: "Gráficos", content: ["Intel UHD Graphics 600"] },
        { title: "Sistema Operativo", content: ["Windows 10 Home, 64 Bits"] },
        { title: "Formato", content: ["Mini PC"] },
      ],
      img: "1_337_1.jpg",
      precos: { normal: "289.90", desconto: null },
      ribbons: { novo: true, saldos: false },
      vendas: 2,
    },
    {
      id: "3",
      title: "Portátil Asus Zenbook 14",
      categorias: {
        categoria: "Computadores",
        subCategoria: "Portáteis",
        subCategoria2: "Notebooks",
      },
      specs: [
        { title: "Marca", content: ["ASUS"] },
        { title: "Armazenamento", content: ["SSD 1TB M.2 NVMe"] },
        { title: "CPU", content: ["Intel Core i5-1135G7"] },
        { title: "RAM", content: ["8GB LPDDR4X onboard (não expansível)"] },
        { title: "Gráficos", content: ["Intel Iris Xe Graphics"] },
        { title: "Sistema Operativo", content: ["Windows 10 Home, 64 Bits"] },
        { title: "Tipo teclado", content: ["TKL"] },
        { title: "Ecrã touch", content: ["Não"] },
        { title: "Tamanho ecrã", content: ['14"'] },
        { title: "Resolução", content: ["1920 x 1080"] },
        { title: "Taxa de atualização", content: [] },
      ],
      img: "1_339_8.jpg",
      precos: { normal: "999.90", desconto: null },
      ribbons: { novo: true, saldos: false },
      vendas: 3,
    },
    {
      id: "4",
      title: "SSD M.2 2280 Gigabyte Aorus Gen4 1TB",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Armazenamento",
        subCategoria2: null,
      },
      specs: [
        { title: "Marca", content: ["Gigabyte"] },
        { title: "Formato", content: ["M.2 2280"] },
        { title: "Capacidade", content: ["1TB"] },
        { title: "Interface", content: ["NVMe™ PCIe Ger 4.0 x4 pistas"] },
      ],
      img: "1_p030470_2.jpg",
      precos: { normal: "187.90", desconto: null },
      ribbons: { novo: false, saldos: false },
      vendas: 4,
    },
    {
      id: "5",
      title: "Teclado Mecânico Asus Sagaris",
      categorias: {
        categoria: "Periféricos",
        subCategoria: "Ratos e Teclados",
        subCategoria2: "Teclados",
      },
      specs: [
        { title: "Marca", content: ["Asus"] },
        { title: "DPI", content: [] },
        { title: "Layout teclado", content: ["US"] },
        { title: "Formato teclado", content: ["Full-size"] },
        { title: "Iluminação", content: ["RGB"] },
        { title: "Interruptores", content: ["Cherry MX Blue"] },
        { title: "Capacidade", content: ["1TB"] },
        { title: "Conexão", content: ["USB-A"] },
      ],
      img: "1085_1.jpg",
      precos: { normal: "149.90", desconto: "54.90" },
      ribbons: { novo: true, saldos: true },
      vendas: 5,
    },
    {
      id: "6",
      title: 'Portátil MSI 15.6" GF63 Thin',
      categorias: {
        categoria: "Computadores",
        subCategoria: "Portáteis",
        subCategoria2: "Gaming",
      },
      specs: [
        { title: "Marca", content: ["MSI"] },
        { title: "Armazenamento", content: ["SSD 512GB NVMe PCIe"] },
        { title: "CPU", content: ["Intel Core i7-10750H"] },
        { title: "RAM", content: ["16GB (1x16GB) DDR4 2666MHz"] },
        {
          title: "RAM",
          content: [
            "2 x Slots SO-DIMM (1 x livre / 1 x ocupado) p/ expansibilidade total até 64GB",
          ],
        },
        { title: "Gráficos", content: ["Intel UHD Graphics"] },
        {
          title: "Gráficos",
          content: ["NVIDIA GeForce GTX 1650 Ti 4GB GDDR6"],
        },
        { title: "Sistema Operativo", content: ["Não incluído"] },
        { title: "Tipo teclado", content: ["TKL"] },
        { title: "Ecrã touch", content: ["Não"] },
        { title: "Tamanho ecrã", content: ["15.6"] },
        { title: "Resolução", content: ["1920 x 1080"] },
        { title: "Taxa de atualização", content: ["144Hz"] },
      ],
      img: "MSI156.jpg",
      precos: { normal: "1199.90", desconto: "949.90" },
      ribbons: { novo: true, saldos: true },
      vendas: 6,
    },
    {
      id: "7",
      title: "All-in-One HP Pavilion 24-k0003np",
      categorias: {
        categoria: "Computadores",
        subCategoria: "Desktops",
        subCategoria2: "All-in-One",
      },
      specs: [
        { title: "Marca", content: ["HP"] },
        { title: "Armazenamento", content: ["SSD 512GB NVMe M.2"] },
        { title: "CPU", content: ["Intel Core i5-10400T"] },
        { title: "RAM", content: ["1x8GB SDRAM DDR4-2666MHz"] },
        {
          title: "RAM",
          content: [
            "2 x Slots SDRAM (1 x livre / 1 x ocupado) p/ expansibilidade total até 32GB",
          ],
        },
        { title: "Gráficos", content: ["Intel UHD Graphics 630"] },
        { title: "Sistema Operativo", content: ["Não incluído"] },
        { title: "Formato", content: ["All-in-One"] },
      ],
      img: "1_292_12.jpg",
      precos: { normal: "899.90", desconto: null },
      ribbons: { novo: false, saldos: false },
      vendas: 7,
    },
    {
      id: "8",
      title: "Processador Intel Core i5-10600KF 6-Core 4.1GHz c/ Turbo 4.8GHz",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Processadores",
        subCategoria2: "Intel",
      },
      specs: [
        { title: "Série", content: ["Intel Core i5"] },
        { title: "Socket", content: ["LGA 1200"] },
        { title: "Núcleos", content: ["6"] },
        { title: "Gráficos", content: ["Não"] },
        { title: "Cooler incluído", content: ["Não"] },
      ],
      img: "sem-ti_tulo-178_1.jpg",
      precos: { normal: "249.90", desconto: null },
      ribbons: { novo: false, saldos: false },
      vendas: 8,
    },
    {
      id: "9",
      title: "Processador AMD Ryzen 5 3600XT Hexa-Core 3.8GHz c/ Turbo 4.5GHz",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Processadores",
        subCategoria2: "AMD",
      },
      specs: [
        { title: "Série", content: ["Ryzen 5"] },
        { title: "Socket", content: ["AM4"] },
        { title: "Núcleos", content: ["6"] },
        { title: "Gráficos", content: ["Não"] },
        { title: "Cooler incluído", content: ["Sim"] },
      ],
      img: "1_p025452.jpg",
      precos: { normal: "259.90", desconto: null },
      ribbons: { novo: false, saldos: false },
      vendas: 9,
    },
    {
      id: "10",
      title: "Placa Gráfica Gigabyte Radeon RX 6800 Gaming 16GB OC",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Placas gráficas",
        subCategoria2: "AMD",
      },
      specs: [
        { title: "Memória", content: ["16GB"] },
        { title: "Gama", content: ["Gaming"] },

        { title: "Gráficos", content: ["AMD Radeon RX 6800"] },
        { title: "Portas I/O", content: ["2 x DisplayPort 1.4a"] },
        { title: "Portas I/O", content: ["2 x HDMI 2.1"] },
      ],
      img: "kjf_1.jpg",
      precos: { normal: "744.90", desconto: null },
      ribbons: { novo: false, saldos: false },
      vendas: 10,
    },
    {
      id: "11",
      title: "Placa Gráfica Gigabyte GeForce RTX 3090 Aorus Xtreme 24GB",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Placas gráficas",
        subCategoria2: "NVIDIA",
      },
      specs: [
        { title: "Memória", content: ["24GB"] },
        { title: "Gama", content: ["Gaming"] },
        { title: "Gráficos", content: ["GeForce RTX 3090"] },
        { title: "Portas I/O", content: ["3 x DisplayPort 1.4a"] },
        { title: "Portas I/O", content: ["2 x HDMI 2.1"] },
        { title: "Portas I/O", content: ["1 x HDMI 2.0"] },
      ],
      img: "1_342_25.jpg",
      precos: { normal: "1949.90", desconto: null },
      ribbons: { novo: false, saldos: false },
      vendas: 11,
    },
    {
      id: "12",
      title: "Fonte de Alimentação Seasonic Prime Titanium 600W Full Modular",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Modulares",
      },
      specs: [
        { title: "Marca", content: ["Seasonic"] },
        { title: "Eficiência", content: ["80 PLUS Titanium"] },
        { title: "Cablagem", content: ["Full Modular"] },
        { title: "Potência", content: ["600w"] },
      ],
      img: "product-p011502-10173.jpg",
      precos: { normal: "227.00", desconto: "199.90" },
      ribbons: { novo: false, saldos: true },
      vendas: 12,
    },
    {
      id: "13",
      title: "Fonte de Alimentação Corsair CX450",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Não Modulares",
      },
      specs: [
        { title: "Marca", content: ["Corsair"] },
        { title: "Eficiência", content: ["80 PLUS Bronze"] },
        { title: "Cablagem", content: ["Não Modular"] },
        { title: "Potência", content: ["450w"] },
      ],
      img: "product-p015954-56212.jpg",
      precos: { normal: "64.90", desconto: "54.90" },
      ribbons: { novo: false, saldos: true },
      vendas: 13,
    },
    {
      id: "14",
      title:
        "Fonte de Alimentação Nox Hummer X700W 80 PLUS Bronze Semi Modular",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [
        { title: "Marca", content: ["Nox Hummer"] },
        { title: "Eficiência", content: ["80 PLUS Bronze"] },
        { title: "Cablagem", content: ["Semi-Modular"] },
        { title: "Potência", content: ["700w"] },
      ],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
      vendas: 14,
    },
    {
      id: "500",
      title: "Título do produto 1",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "15",
      title: "Título do produto 2",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "16",
      title: "Título do produto 3",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "17",
      title: "Título do produto 4",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "18",
      title: "Título do produto 5",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "19",
      title: "Título do produto 6",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "20",
      title: "Título do produto 7",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "21",
      title: "Título do produto 8",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "22",
      title: "Título do produto 9",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "23",
      title: "Título do produto 10",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "24",
      title: "Título do produto 11",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "25",
      title: "Título do produto 12",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "26",
      title: "Título do produto 13",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "27",
      title: "Título do produto 14",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "28",
      title: "Título do produto 15",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "29",
      title: "Título do produto 16",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "30",
      title: "Título do produto 17",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "31",
      title: "Título do produto 18",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "32",
      title: "Título do produto 19",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "33",
      title: "Título do produto 20",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "34",
      title: "Título do produto 21",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "35",
      title: "Título do produto 22",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "36",
      title: "Título do produto 23",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "37",
      title: "Título do produto 24",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "38",
      title: "Título do produto 25",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "39",
      title: "Título do produto 26",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "40",
      title: "Título do produto 27",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "41",
      title: "Título do produto 28",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "413",
      title: "Título do produto 29",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "4133",
      title: "Título do produto 30",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "41336",
      title: "Título do produto 31",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "413361",
      title: "Título do produto 32",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "4133618",
      title: "Título do produto 33",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "41336183",
      title: "Título do produto 34",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "413361837",
      title: "Título do produto 35",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "61837",
      title: "Título do produto 36",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "37",
      title: "Título do produto 37",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "3437",
      title: "Título do produto 38",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "343743",
      title: "Título do produto 39",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "3433",
      title: "Título do produto 40",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "433",
      title: "Título do produto 41",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "433483",
      title: "Título do produto 42",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "483",
      title: "Título do produto 43",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "68.90", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "484",
      title: "A",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "1", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "485",
      title: "B",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "2", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "486",
      title: "B",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "2", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "487",
      title: "C",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "3", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "488",
      title: "D",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "4", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "489",
      title: "E",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "5", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "490",
      title: "F",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "6", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "491",
      title: "G",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "7", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "492",
      title: "H",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "8", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "493",
      title: "I",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "9", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "494",
      title: "J",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "10", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "495",
      title: "K",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "11", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "496",
      title: "L",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "12", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "497",
      title: "M",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "13", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "498",
      title: "N",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "14", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "499",
      title: "O",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "15", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "500",
      title: "P",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "16", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "501",
      title: "Q",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "17", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "502",
      title: "R",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "18", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "503",
      title: "S",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "19", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "504",
      title: "T",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "20", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "505",
      title: "U",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "21", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "506",
      title: "V",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "22", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "507",
      title: "W",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "23", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "508",
      title: "X",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "24", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "509",
      title: "Y",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "25", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
    {
      id: "510",
      title: "Z",
      categorias: {
        categoria: "Componentes",
        subCategoria: "Fontes de Alimentação",
        subCategoria2: "Semi-Modulares",
      },
      specs: [],
      img: "product-p016157-55456_2.jpg",
      precos: { normal: "26", desconto: null },
      ribbons: { novo: false, saldos: false },
    },
  ],
};
